auth0-samples/auth0-ionic-samples

05-Rules/.bowerrc
05-Rules/.editorconfig
05-Rules/.gitignore
05-Rules/README.md
05-Rules/bower.json
05-Rules/config.xml
05-Rules/gulpfile.js
05-Rules/hooks/README.md
05-Rules/hooks/after_prepare/010_add_platform_class.js
05-Rules/ionic.project
05-Rules/package.json
05-Rules/scss/ionic.app.scss
05-Rules/www/app/account/login.controller.js
05-Rules/www/app/account/login.html
05-Rules/www/app/app.js
05-Rules/www/app/auth0.variables.js
05-Rules/www/app/home/home.controller.js
05-Rules/www/app/home/home.html
05-Rules/www/css/style.css
05-Rules/www/index.html

add Rules example

---

06-Authorization/.bowerrc
06-Authorization/.editorconfig
06-Authorization/.gitignore
06-Authorization/README.md
06-Authorization/bower.json
06-Authorization/config.xml
06-Authorization/gulpfile.js
06-Authorization/hooks/README.md
06-Authorization/hooks/after_prepare/010_add_platform_class.js
06-Authorization/ionic.project
06-Authorization/package.json
06-Authorization/scss/ionic.app.scss
06-Authorization/www/app/account/login.controller.js
06-Authorization/www/app/account/login.html
06-Authorization/www/app/app.js
06-Authorization/www/app/auth0.variables.js
06-Authorization/www/app/home/home.controller.js
06-Authorization/www/app/home/home.html
06-Authorization/www/css/style.css
06-Authorization/www/index.html

Add Authorization example

---

07-Calling-Api/.bowerrc
07-Calling-Api/.editorconfig
07-Calling-Api/.gitignore
07-Calling-Api/README.md
07-Calling-Api/bower.json
07-Calling-Api/config.xml
07-Calling-Api/gulpfile.js
07-Calling-Api/hooks/README.md
07-Calling-Api/hooks/after_prepare/010_add_platform_class.js
07-Calling-Api/ionic.project
07-Calling-Api/package.json
07-Calling-Api/scss/ionic.app.scss
07-Calling-Api/www/app/account/login.controller.js
07-Calling-Api/www/app/account/login.html
07-Calling-Api/www/app/app.js
07-Calling-Api/www/app/auth0.variables.js
07-Calling-Api/www/app/home/home.controller.js
07-Calling-Api/www/app/home/home.html
07-Calling-Api/www/css/style.css
07-Calling-Api/www/index.html

Add Calling APIs example

---

08-MFA/.bowerrc
08-MFA/.editorconfig
08-MFA/.gitignore
08-MFA/README.md
08-MFA/bower.json
08-MFA/config.xml
08-MFA/gulpfile.js
08-MFA/hooks/README.md
08-MFA/hooks/after_prepare/010_add_platform_class.js
08-MFA/ionic.project
08-MFA/package.json
08-MFA/scss/ionic.app.scss
08-MFA/www/app/account/login.controller.js
08-MFA/www/app/account/login.html
08-MFA/www/app/app.js
08-MFA/www/app/auth0.variables.js
08-MFA/www/app/home/home.controller.js
08-MFA/www/app/home/home.html
08-MFA/www/css/style.css
08-MFA/www/index.html

Add MFA example

---

09-Customizing-Lock/.bowerrc
09-Customizing-Lock/.editorconfig
09-Customizing-Lock/.gitignore
09-Customizing-Lock/README.md
09-Customizing-Lock/bower.json
09-Customizing-Lock/config.xml
09-Customizing-Lock/gulpfile.js
09-Customizing-Lock/hooks/README.md
09-Customizing-Lock/hooks/after_prepare/010_add_platform_class.js
09-Customizing-Lock/ionic.project
09-Customizing-Lock/package.json
09-Customizing-Lock/scss/ionic.app.scss
09-Customizing-Lock/www/app/account/login.controller.js
09-Customizing-Lock/www/app/account/login.html
09-Customizing-Lock/www/app/app.js
09-Customizing-Lock/www/app/auth0.variables.js
09-Customizing-Lock/www/app/home/home.controller.js
09-Customizing-Lock/www/app/home/home.html
09-Customizing-Lock/www/css/style.css
09-Customizing-Lock/www/index.html

Add customizing Lock example

---

Server/.gitignore
Server/README.md
Server/package.json
Server/server.js

Add simple NodeJS server

---

06-Authorization/.bowerrc
06-Authorization/.editorconfig
06-Authorization/.gitignore
06-Authorization/README.md
06-Authorization/bower.json
06-Authorization/config.xml
06-Authorization/gulpfile.js
06-Authorization/hooks/README.md
06-Authorization/hooks/after_prepare/010_add_platform_class.js
06-Authorization/ionic.config.json
06-Authorization/package.json
06-Authorization/scss/ionic.app.scss
06-Authorization/www/app.js
06-Authorization/www/app.run.js
06-Authorization/www/auth0.variables.js
06-Authorization/www/components/auth/auth.service.js
06-Authorization/www/components/home/home.controller.js
06-Authorization/www/components/home/home.html
06-Authorization/www/components/login/login.controller.js
06-Authorization/www/components/login/login.html
06-Authorization/www/index.html
06-Authorization/www/style.css

06-Authorization Lock 10 sample updates

06-Authorization Lock 10 sample updates

---

07-Calling-Api/.bowerrc
07-Calling-Api/.editorconfig
07-Calling-Api/.gitignore
07-Calling-Api/README.md
07-Calling-Api/bower.json
07-Calling-Api/config.xml
07-Calling-Api/gulpfile.js
07-Calling-Api/hooks/README.md
07-Calling-Api/hooks/after_prepare/010_add_platform_class.js
07-Calling-Api/ionic.config.json
07-Calling-Api/package.json
07-Calling-Api/scss/ionic.app.scss
07-Calling-Api/www/app.js
07-Calling-Api/www/app.run.js
07-Calling-Api/www/auth0.variables.js
07-Calling-Api/www/components/auth/auth.service.js
07-Calling-Api/www/components/home/home.controller.js
07-Calling-Api/www/components/home/home.html
07-Calling-Api/www/components/login/login.controller.js
07-Calling-Api/www/components/login/login.html
07-Calling-Api/www/index.html
07-Calling-Api/www/style.css

07-Calling-Api Lock 10 sample updates

07-Calling-Api Lock 10 sample updates

---

08-MFA/.bowerrc
08-MFA/.editorconfig
08-MFA/.gitignore
08-MFA/README.md
08-MFA/bower.json
08-MFA/config.xml
08-MFA/gulpfile.js
08-MFA/hooks/README.md
08-MFA/hooks/after_prepare/010_add_platform_class.js
08-MFA/ionic.config.json
08-MFA/package.json
08-MFA/scss/ionic.app.scss
08-MFA/www/app.js
08-MFA/www/app.run.js
08-MFA/www/auth0.variables.js
08-MFA/www/components/auth/auth.service.js
08-MFA/www/components/home/home.controller.js
08-MFA/www/components/home/home.html
08-MFA/www/components/login/login.controller.js
08-MFA/www/components/login/login.html
08-MFA/www/index.html

08-MFA Lock 10 sample updates

---

09-Customizing-Lock/.bowerrc
09-Customizing-Lock/.editorconfig
09-Customizing-Lock/.gitignore
09-Customizing-Lock/README.md
09-Customizing-Lock/bower.json
09-Customizing-Lock/config.xml
09-Customizing-Lock/gulpfile.js
09-Customizing-Lock/hooks/README.md
09-Customizing-Lock/hooks/after_prepare/010_add_platform_class.js
09-Customizing-Lock/ionic.config.json
09-Customizing-Lock/package.json
09-Customizing-Lock/scss/ionic.app.scss
09-Customizing-Lock/www/app.js
09-Customizing-Lock/www/app.run.js
09-Customizing-Lock/www/auth0.variables.js
09-Customizing-Lock/www/components/auth/auth.service.js
09-Customizing-Lock/www/components/home/home.controller.js
09-Customizing-Lock/www/components/home/home.html
09-Customizing-Lock/www/components/login/login.controller.js
09-Customizing-Lock/www/components/login/login.html
09-Customizing-Lock/www/index.html

09-Customizing-Lock Lock 10 sample updates

09-Customizing-Lock Lock 10 sample updates

---

00-Starter-Seed/README.md

00-Starter-Seed

---

02-Custom-Login/README.md

02-Custom-Login

---

03-User-Profile/README.md

03-User-Profile

---

04-Linking-Accounts/README.md

04-Linking-Accounts

---

06-Authorization/README.md

06-Authorization

---

07-Calling-Api/README.md

07-Calling-Api

---

09-Customizing-Lock/README.md

09-Customizing-Lock

---

00-Starter-Seed/bower.json
01-Login/bower.json
02-Custom-Login/bower.json
03-User-Profile/bower.json
04-Linking-Accounts/bower.json
05-Rules/bower.json
06-Authorization/bower.json
07-Calling-Api/bower.json
08-MFA/bower.json
09-Customizing-Lock/bower.json

Update bower dependencies

---

README.md

Add the troubleshooting section

Add the troubleshooting section

---

08-MFA/www/components/home/home.html

Add text to the main home screen

Add text to the main home screen

---

07-Calling-Api/www/components/home/home.controller.js

Server error message fix

---

01-Login/README.md
02-Custom-Login/README.md
03-User-Profile/README.md
04-Linking-Accounts/README.md
05-Rules/README.md
06-Authorization/README.md
07-Calling-Api/README.md
08-MFA/README.md
09-Customizing-Lock/README.md

updated all the readme.md

---

angular/src/app/app.component.ts

Currently when logging in, the app doesn't update to show the authenticated state. Wrapping it in `ngZone.run` should cause the app to update once the login callback has been handled.
A similar PR will be made to the docs repo to explain this change.
Fixes #71

Ensure Angular app updates after login callback

---

react/package-lock.json

This PR updates the `package-lock.json` file for the React example to bring our dependencies up to their latest versions to resolve vulnerabilities identified in dependencies' previous versions.

Security: update React dependencies lockfile

---

angular/package-lock.json
react/package-lock.json

Aggregates all the other PRs to update a single dependency at a time. Tested manually in an iOS simulator.
Closes #433
Closes #432
Closes #431
Closes #430
Closes #429
Closes #428
Closes #426
Closes #422
Closes #421
Closes #420

update dependencies for React & Angular samples

---

react/package-lock.json
react/package.json
react/src/components/LoginButton.tsx
react/src/components/LogoutButton.tsx
react/src/index.tsx

Updates the ionic+react sample for the v2 release, also updates some dependencies to latest

[SDK-3828] Update to v2 auth0-react

---

angular/package-lock.json

Update dependencies locally, should resolve the other dependabot PRs that have been raised but fail CI.

chore: update Angular dependencies

---

angular/package-lock.json

chore: run npm update && npm audit fix

---

.github/ISSUE_TEMPLATE/Bug Report.yml
.github/ISSUE_TEMPLATE/Feature Request.yml

This PR adds the README of the Vue sample to the list of README links in the GitHub issue forms.

Add the Vue sample's README to the list of links
